
name: Pull Request
on: [push]

jobs:
  build:
    name: Test on node
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]
        
    steps:
    - uses: actions/checkout@master
    - name: Test
      # uses: actions/checkout@master
      ## https://github.com/julio899/j899/actions/workflows/pull_request.yml
