on: pull_request
name: Pull Request
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest]
        
    steps:
    - uses: actions/checkout@master
    - name: Test
      uses: julio899/j899@master
